### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by baweaver**
I'd noticed this package was pulling in some older dependencies which causes a lot of similar packages of different versions to be installed. 

All tests currently pass given the upgraded versions of packages.

Thank you for your time in reading!

### CODE REVIEW

**Comment by trabus** [comment]
Thanks for the PR!
If you could update the travis.yml file [to support yarn](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), your tests should pass hopefully. I was also wondering if you could add some newer Node targets while you're in there, like 4, 6, and maybe even 7?

**Comment by baweaver** [comment]
Yeah, not a problem. I'll get to that in just a second, just have to find which Sublime window it's hidden in. Been hunting down older versions of Lodash for a while now :)

**Comment by baweaver** [comment]
Are you wanting to maintain the older versions of Node on there as well? I think that `0.10` was EOL, not sure on the others.

**Comment by trabus** [comment]
Sorry for the delayed response, my machine died shortly after replying on Saturday. I wouldn't mind keeping 0.12 support in place, but it's not critical. I think this is good as is, will merge and cut a new release today. Thanks for the PR!

**Pull request merged**
